// <auto-generated />
namespace To_show.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Infoclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Infoclass));
        
        string IMigrationMetadata.Id
        {
            get { return "202006161147150_Info class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
